# Generated by Django 2.0.13 on 2019-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
