# Generated by Django 2.0.13 on 2019-02-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_auto_20190216_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='User',
            old_name='email_address',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='User',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='User',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
