# Generated by Django 2.0.13 on 2019-02-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0003_auto_20190216_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
